dist: trusty
sudo: required

# branches:
#   only:
#   - master

os:
  - linux

compiler:
  - gcc

language:
  - c

matrix:
  include:
    - os: linux
      dist: trusty
      env: TARGET=linux32
    - os: linux
      dist: trusty
      env: TARGET=linux64
    - os: linux
      dist: trusty
      env: TARGET=win32
    - os: linux
      dist: trusty
      env: TARGET=win64

before_install:
  - export | sort
  - env | sort
  - sudo apt-get update
  - sudo apt-get -y install build-essential gcc-multilib python3-dev python3-pip ninja-build mingw-w64
  - virtualenv .env --python=python3
  - . .env/bin/activate
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt

script:
  - mkdir build_${TARGET}
  - meson build_${TARGET} --cross-file cross-compilation_${TARGET}.txt
  - ninja -v -C build_${TARGET}
  - ninja -v test -C build_${TARGET}

