name: actions
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [linux-amd64, linux-i686, linux-armhf, linux-aarch64, windows-x64, windows-x86]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: |
             sudo apt-get update
             sudo apt-get -y install build-essential python3-virtualenv python3-dev python3-pip ninja-build cmake gcc-multilib
             virtualenv .venv --python=python3
             . .venv/bin/activate
             pip3 install --upgrade pip
             pip3 install -r requirements.txt
      - name: Prepare2
        if: ${{ matrix.target }}=='linux-armhf'
        run: sudo apt-get -y install gcc-arm-linux-gnueabihf pkg-config-arm-linux-gnueabihf libc6-dev-armhf-cross
      - name: Prepare3
        if: ${{ matrix.target }}=='linux-aarch64'
        run: sudo apt-get -y install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
      - name: Build
        run: |
             ./.venv/bin/meson build-${{ matrix.target }} --buildtype=release --cross-file tools/cross-compilation/${{ matrix.target }}.txt
             ninja -v -C build-${{ matrix.target }}
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: build-${{ matrix.target }}/qwprogs.so
